// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBycrxa65JOoeHp-S64Nf3cYHLh95A4UPI',
    appId: '1:655421100556:web:4a128e51fd3a3fb44dd429',
    messagingSenderId: '655421100556',
    projectId: 'weather-app-39b08',
    authDomain: 'weather-app-39b08.firebaseapp.com',
    storageBucket: 'weather-app-39b08.firebasestorage.app',
    measurementId: 'G-G10Q0GWNDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpofXe5BC8QezNHg0r5tkOX9SNZuOdxsQ',
    appId: '1:655421100556:android:c89d88e52a09a46a4dd429',
    messagingSenderId: '655421100556',
    projectId: 'weather-app-39b08',
    storageBucket: 'weather-app-39b08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnMSrnX9xHGLIhiRB9wSQ9-ySEG5rn-aY',
    appId: '1:655421100556:ios:61aac834e7ede0214dd429',
    messagingSenderId: '655421100556',
    projectId: 'weather-app-39b08',
    storageBucket: 'weather-app-39b08.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnMSrnX9xHGLIhiRB9wSQ9-ySEG5rn-aY',
    appId: '1:655421100556:ios:61aac834e7ede0214dd429',
    messagingSenderId: '655421100556',
    projectId: 'weather-app-39b08',
    storageBucket: 'weather-app-39b08.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBycrxa65JOoeHp-S64Nf3cYHLh95A4UPI',
    appId: '1:655421100556:web:c99d4ba17b1ab5994dd429',
    messagingSenderId: '655421100556',
    projectId: 'weather-app-39b08',
    authDomain: 'weather-app-39b08.firebaseapp.com',
    storageBucket: 'weather-app-39b08.firebasestorage.app',
    measurementId: 'G-MWYEWSK0PY',
  );
}
